Repository Illarion-eV/Illarion-Content, pull requests merged in 2021-03, with the labels that each got.

#239 Text improvements
  npc/eleanor_fairbanks.npc
  npc/numila_irunnleh.npc
Labels: text

#244 Fix custom lookAt for claypits
  item/id_1206_claypit.lua
Labels: bug

#243 Prevent NPCs from buying gemmed items
  npc/base/trade.lua
Labels: improvement
